{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.configmap.configMapName}}
data:
  {{- range $key, $value := .Values.configmap.data }}
    {{ $key }}: "{{ $value }}"
  {{- end }} 
{{- end }} 